<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Subject extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'code',
        'teacher_id'
    ];

    // public static function boot()
    // {
    //     parent::boot(); // TODO: Change the autogenerated stub
    //     static::addGlobalScope('teacher_id', function (Builder $builder) {
    //         if (auth()->check() && !auth()->user()->is_admin) {
    //             $teacher = Teacher::where('user_id', auth()->id())->firstOrfail();
    //             return $builder->where('teacher_id', $teacher->id);
    //         }
    //     });
    // }

    public function questionSets()
    {
        return $this->hasMany(QuestionSet::class);
    }
    public function teacher()
    {
        return $this->belongsTo(Teacher::class);
    }

    public function topics()
    {
        return $this->hasMany(Topic::class);
    }
}
